# We cannot enable container-based infrastructure for now since we need TeXlive
# from a PPA
#sudo: false
sudo: true
dist: trusty


# Work around travis bug:
# https://github.com/travis-ci/travis-ci/issues/4948#issuecomment-152839021
#language: generic
language: python

python:
    - '2.7'
    - '3.4'
    #- '3.5.0'

virtualenv:
  system_site_packages: true

cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install python-matplotlib python3-matplotlib
  - sudo apt-get -y install python-pytest python3-pytest
  - sudo apt-get -y install python-pip python3-pip
  - sudo apt-get -y install python-yaml python3-yaml
  - sudo -H pip install -r requirements.txt

install:
  - sudo -H pip install .
  - sudo -H pip3 install .

script:
  - cd test/
  - pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
